### ISSUE TITLE
Using Your Work to Learn From

### ISSUE THREAD

**Issue by ZellW** [Z3tt/TidyTuesday#2]
I an using your code to learn how you produced such beautiful output.  I am running into an issue.  I hope you'll find time to teach me how to overcome this.

When you build your theme, you use `plot.margin = margin(30, 60, 30, 60)`  That errors on me.  I think you need to use `plot.margin = unit(c(30, 60, 30, 60), "mm")` but I do not know what units (like I have "mm") to use to replicate your output.  Do you have any ideas?

Really great work!  Thank you for sharing.

**Comment by z3tt** [comment]
Hi Cliff, thanks for the feedback! I never need to specify any units - which OS are you using? The default of `ggsave()` should be inches (`in`), does this work?

**Comment by ZellW** [comment]
OK, I cannot explain it but now the plot.margin is working as you have it.  So sorry to trouble you.  Thank you for your work.  I am still gigging through it and learning lots.
