### ISSUE TITLE
Error in Astronauts Tidy Tuesday

### ISSUE THREAD

**Issue by makixGRA** [Z3tt/TidyTuesday#3]
Hi Cedric! I've been reproducing your code and I've faced with this error in the first summarize, with the sentence nationality = unique(nationality). The message is: "Error: Column `nationality` must be length 1 (a summary value), not 2".

**Comment by z3tt** [comment]
Hi Miguel, thanks for the feedback! I am not sure why it isn't working for you, for me it works. Anyway, this was some leftover code from previous trials so I have removed it now. In general, that error tells that there is 2 nationalities for at least one of the group combinations.
